// Staff
export const REQUEST_STAFF = "REQUEST_STAFF";
export const RECEIVE_STAFF = "RECEIVE_STAFF";
export const INVALIDATE_STAFF = "INVALIDATE_STAFF";
export const ERROR_STAFF = "ERROR_STAFF";

// Contact
export const REQUEST_CONTACT_FORM = "REQUEST_CONTACT_FORM";
export const SUBMIT_CONTACT_FORM = "SUBMIT_CONTACT_FORM";
export const ERROR_CONTACT_FORM = "ERROR_CONTACT_FORM";

// Categories
export const REQUEST_CATEGORIES = "REQUEST_CATEGORIES";
export const RECEIVE_CATEGORIES = "RECEIVE_CATEGORIES";
export const INVALIDATE_CATEGORIES = "INVALIDATE_CATEGORIES";
export const ERROR_CATEGORIES = "ERROR_CATEGORIES";

// Posts
export const REQUEST_POSTS = "REQUEST_POSTS";
export const RECEIVE_POSTS = "RECEIVE_POSTS";
export const ERROR_POSTS = "ERROR_POSTS";


